using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Text;
using TaskFlow.Modules.Users.Domain.Entities;

namespace TaskFlow.Modules.Users.Infrastructure.Configurations
{
    public class EmailVerificationTokenConfiguration : IEntityTypeConfiguration<EmailVerificationToken>
    {
        public void Configure(
        EntityTypeBuilder<EmailVerificationToken> builder)
        {
            builder.ToTable("EmailVerificationTokens");

            builder.HasKey(x => x.Id);

            // Application is the source of truth for entity identity.
            // IDs are generated by the application rather than by SQL Server.
            builder.Property(x => x.Id)
                .ValueGeneratedNever();


            //builder.Property(x => x.Id)
            //    .HasDefaultValueSql("NEWSEQUENTIALID()");

            builder.Property(x => x.UserId)
                .IsRequired();

            builder.Property(x => x.TokenHash)
                .HasMaxLength(200)
                .IsRequired();

            builder.Property(x => x.ExpiresAtUTC)
                .IsRequired();

            builder.Property(x => x.UsedAtUTC);

            builder.Property(x => x.CreatedAtUTC)
                .IsRequired();

            // ------------------------------
            // Indexes
            // ------------------------------

            builder.HasIndex(x => x.TokenHash)
                .IsUnique();

            // ------------------------------
            // Relationship
            // ------------------------------

            builder.HasOne<User>()
                .WithMany()
                .HasForeignKey(x => x.UserId)
                .OnDelete(DeleteBehavior.Cascade);
        }
    }
}
