using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Text;
using TaskFlow.Modules.Users.Domain.Entities;


namespace TaskFlow.Modules.Users.Infrastructure.Configurations
{
    public class UserConfiguration :IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> builder) 
        {


            // ----- All SQL related rules stay here like lengths, indexes and constraints  ----------
            // Table
            // ------------------------------
            builder.ToTable("Users");

            // ------------------------------
            // Primary Key
            // ------------------------------
            builder.HasKey(x => x.Id);
            
            // Application is the source of truth for entity identity.
            // IDs are generated by the application rather than by SQL Server.
            builder.Property(x => x.Id)
                .ValueGeneratedNever();

            //Removed because now application is the source of truth for Entity identity and Ids are now generated from the application rather than sql.
            //builder.Property(x=>x.Id).HasDefaultValueSql(
            //        "NEWSEQUENTIALID()");

            // ------------------------------
            // Properties
            // ------------------------------
            builder.Property(x => x.FirstName)
                .HasMaxLength(200)
                .IsRequired();

            builder.Property(x => x.LastName)
                .HasMaxLength(200);
                

            builder.Property(x => x.Email)
                .HasMaxLength(200)
                .IsRequired();

            builder.Property(x => x.PasswordHash)
                .IsRequired();

            builder.Property(x => x.IsActive)
                .IsRequired();

            builder.Property(x => x.CreatedAtUTC)
                .IsRequired();

            builder.Property(x => x.EmailVerifiedAtUTC);

            // ------------------------------
            // Indexes
            // ------------------------------
            builder.HasIndex(x => x.Email)
                .IsUnique();
        }
    }
}
