@TaskFlow.Api_HostAddress = https://localhost:7111

### Get User
GET {{TaskFlow.Api_HostAddress}}/api/user
Accept: application/json

### Create User
POST {{TaskFlow.Api_HostAddress}}/api/user
Content-Type: application/json
Accept: application/json

{
  "name": "Muhammad Hassan Amin",
  "email": "has@gmail.com",
  "password": "5555",
  "role": "Admin"
}

### Update User
PUT https://localhost:7111/api/user/1
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Name",
  "email": "updated@gmail.com"
}

